spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**
        - id: event-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/events/**, /api/v1/catalog/**
        - id: seat-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/shows/**, /api/v1/seats/**
        - id: booking-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/bookings/**
        - id: payment-service-route
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/payments/**
        - id: notification-service-route
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/notifications/**
        - id: analytics-service-route
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/analytics/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
