spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
logging:
  level:
    root: INFO
    com.ticketbooking.user: INFO
